export enum WorkItemState {
  OPEN = 'OPEN',
  TRIAGED = 'TRIAGED',
  PLANNED = 'PLANNED',
  APPROVED_FOR_DEV = 'APPROVED_FOR_DEV',
  IN_PROGRESS = 'IN_PROGRESS',
  DRAFT_PR = 'DRAFT_PR',
  VALIDATING = 'VALIDATING',
  REVIEWING = 'REVIEWING',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  REVIEW_PASSED = 'REVIEW_PASSED',
  MERGE_READY = 'MERGE_READY',
  MERGED = 'MERGED',
  HUMAN_REQUIRED = 'HUMAN_REQUIRED',
  QUARANTINED = 'QUARANTINED',
  CANCELLED = 'CANCELLED'
}

